# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/projects/amd/test_project/test_project.srcs/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0.xci
# IP: The module: 'mdesign_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projects/amd/test_project/test_project.gen/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mdesign_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/projects/amd/test_project/test_project.gen/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mdesign_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/projects/amd/test_project/test_project.srcs/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0.xci
# IP: The module: 'mdesign_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/projects/amd/test_project/test_project.gen/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mdesign_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/projects/amd/test_project/test_project.gen/sources_1/bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mdesign_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
