domain_path: /home/kai/projects/amd/zuboard/vitis_files/pll_connect/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/kai/xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
