# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/m_constraint.xdc

# Block Designs: bd/mdesign/mdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mdesign || ORIG_REF_NAME==mdesign} -quiet] -quiet

# IP: bd/mdesign/ip/mdesign_zynq_ultra_ps_e_0_0/mdesign_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mdesign_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mdesign_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mdesign/ip/mdesign_top_0_0/mdesign_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mdesign_top_0_0 || ORIG_REF_NAME==mdesign_top_0_0} -quiet] -quiet

# IP: bd/mdesign/ip/mdesign_proc_sys_reset_0_0/mdesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mdesign_proc_sys_reset_0_0 || ORIG_REF_NAME==mdesign_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/projects/amd/test_project/test_project.gen/sources_1/bd/mdesign/mdesign_ooc.xdc
